locales:
  txi:
    name: Ikpeng Keyboards
    description: >-
      Mobile OS keyboards for the Ikpeng language from the Divvun group
      at UiT.
  en:
    name: Ikpeng Keyboards
    description: >-
      Mobile OS keyboards for the Ikpeng language from the Divvun group
      at UiT.
  nb:
    name: Ikpeng tastatur
    description: Mobiltastatur for Ikpeng fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
